### ISSUE TITLE
When you go into the memory game the win sound plays

### ISSUE THREAD

**Issue by Turbobus** [Danilll01/DAT257-Group-Orup#120]
Right now when entering the memory game the first thing you hear is the winning jingle. I also think it plays the card matching sound but it's hard to distinguish.

**Comment by Elin1043** [comment]
Probably becuase the sound sources have "Play On Awake" enabled, but that's just a guess

**Comment by Turbobus** [comment]
You were exactly correct. This is fixed in the linked pull request
