### ISSUE TITLE
Fox starts jumping without pressing play

### ISSUE THREAD

**Issue by Elin1043** [Danilll01/DAT257-Group-Orup#93]
In the music game. When placing nodes the fox starts jumping, it even continues to jump multiple notes ahead without pressing on the play button

**Comment by Turbobus** [comment]
This is because the click movement in the main menu have not yet been commented out / turned of. As it uses the same script when you click in the music game the fox starts jumping to the nearest spot there too.

But good that you make a issue about it 🙂
